### ISSUE TITLE
동적으로 사라지는 엘리먼트에 대한 설명 추가 필요해보입니다.

### ISSUE THREAD

**Issue by flyskyne** [nhnent/tui.component.placeholder#1]
IE7에서 동적으로 구성되는 페이지일 경우 자꾸 오류가 발생하여 확인해보니 `generateOnTargets()`에서 이전 타겟들을 모두 들고 있네요.

```javascript
this.targets = this.targets.concat(selectedTargets);
```

`_getPalceHolderHtml()`에서 타겟이 이미 화면에 없는 엘리먼트라 `util.getStyle(target)` 호출 시 null이 반환되어 오류가 발생하였습니다.

튜토리얼에 화면에서 사라지는 엘리먼트는 `remove()`를 호출해서 placeholder를 없애주어야 한다는 설명이 추가되면 좋겠습니다.

> 동적으로 생성된 태그에 placeholder를 넣고 싶다면 어떻게 해야되나요?
> 
> placeholder를 생성하는 함수의 매개변수로 동적으로 생성된 태그 리스트를 넘기면 한 번에 끝!
> 자세한 사용 방법은 다음 샘플 페이지를 참고하세요.

그리고 `unbindEvnet()`의 다음 구문에서 오류가 발생합니다.

```javascript
if (success) {
    delete target[callbackPropName(eventType)];
}
```
![image](https://cloud.githubusercontent.com/assets/12438945/21419058/b973465a-c868-11e6-8bd1-c34e0e5bb224.png)

**Comment by seonim-ryu** [comment]
안녕하세요. FE개발랩입니다 :)

튜토리얼에 대한 의견 감사드리며,
추가로 문의주신 내용들과 함께 빠른 시일 내 반영할 수 있도록 하겠습니다.

감사합니다.
